template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.9.4/templates/ImageBuilder/amazon-linux-2023-agora-bastian.yaml"
stack_name: "agora-data-manager-github-runner"
stack_tags:
  OwnerEmail: "jessica.britton@sagebase.org"
  CostCenter: "Agora / 112300"
parameters:
  ImageVersion: "1.0.0"
