template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.9.8/templates/ImageBuilder/cis-for-eb-image-pipeline-template.yaml"
stack_name: "cis-for-beanstalk-image-pipeline"
stack_tags:
  OwnerEmail: "it@sagebase.org"
  CostCenter: "Platform Infrastructure / 990300"
parameters:
  ImageVersion: "1.0.0"
